name: Release

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      gh_repo:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:

  release:

    name: Release

    environment: release

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          show-progress: false
          sparse-checkout: .ci

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: assets
          skip-decompress: true

      - run: echo "${GITHUB_WORKSPACE}"

      - name: Checkout release repo
        uses: actions/checkout@v7
        with:
          clean: false
          path: checkout
          fetch-tags: true
          ref: ${{ github.sha }}
          repository: ${{ inputs.gh_repo }}
          show-progress: false
          sparse-checkout:
          token: ${{ secrets.GH_TOKEN }}

      - name: Release
        env:
          GH_REPO: ${{ inputs.gh_repo }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./.ci/release.sh assets checkout

# vim: foldmethod=marker foldlevel=0
