name: Release

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:

  release:

    name: Release

    environment: release

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          sparse-checkout: .ci
          show-progress: false

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: artifacts/new
          skip-decompress: true

      - name: Release
        env:
          GH_REPO: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: ./.ci/release.sh

# vim: foldmethod=marker foldlevel=0
