name: Build

permissions:
  contents: read

on:
  workflow_call:
    inputs: &INPUTS
      jobs:
        description: 'Run the specified list of jobs'
        default: 'default'
        required: false
        type: string
      fail_fast:
        description: 'Stop remaining jobs on failure'
        default: false
        type: boolean
      all_artifacts:
        description: 'Generate all artifacts'
        default: false
        required: false
        type: boolean
      test:
        description: 'Run tests'
        default: true
        required: false
        type: boolean
  workflow_dispatch:
    inputs: *INPUTS

defaults:
  run:
    shell: bash

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
          sparse-checkout: .ci
      - name: Generate outputs
        id: generate
        run: |
          set -o noglob
          ./.ci/build_matrix_generate.sh ${{ inputs.jobs }}
    outputs:
      jobs: ${{ steps.generate.outputs.jobs }}

  emulator:
    needs: prepare
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).emulator != '[]'
    name: Emulator
    uses: ./.github/workflows/build_matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).emulator }}
      fail_fast: ${{ inputs.fail_fast || true }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  platform:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).platform != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: Platform
    uses: ./.github/workflows/build_matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).platform }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

# vim: foldmethod=marker foldlevel=0
