# This workflow is managed by gh actions-lock.

name: Build Matrix

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      cache_epoch:
        required: true
        type: string
      fail_fast:
        required: true
        type: boolean
      jobs:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  build:

    strategy:
      fail-fast: ${{ inputs.fail_fast }}
      matrix:
        include: ${{ fromJSON(inputs.jobs) }}

    name: ${{ matrix.job }}
    runs-on: 'ubuntu-latest'

    steps:

      # Checkout. {{{

      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          clean: false
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          show-progress: false

      # }}}

      - name: Check FFI cdecls are up-to-date
        if: matrix.check_ffi_cdecls
        run: ":"

      - name: Test
        if: matrix.tests
        run: ":"

      # Generate & upload artifacts. {{{

      - name: Generate artifacts
        if: matrix.artifacts
        run: >
          ./.ci/artifacts_generate.sh
          '${{ matrix.id }}'
          '${{ matrix.macosx_deployment_target }}'

      - name: Upload artifacts
        if: matrix.artifacts
        uses: $/.github/actions/upload-artifacts
        with:
          patterns: |
            koreader-*.7z
            koreader-*.apk
            koreader-*.AppImage
            koreader_*.deb
            koreader-*.tar.xz
            koreader-*.targz
            koreader-*.zip

      # }}}

# vim: foldmethod=marker foldlevel=0
