name: Build Matrix

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      # Mandatory.
      jobs:
        required: true
        type: string
      # Optional.
      fail_fast:
        default: false
        type: boolean
      all_artifacts:
        default: false
        type: boolean
      test:
        default: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:

  build:

    if: inputs.jobs != '' && true || false

    strategy:
      fail-fast: ${{ inputs.fail_fast }}
      # matrix: ${{ fromJSON(inputs.jobs != '' && format('{{"include":{0}}}', inputs.jobs) || '{}') }}
        # # include: ${{ fromJSON(inputs.jobs != '' && inputs.jobs || '[]') }}
        # include: ${{ fromJSON('[]') }}

    name: ${{ matrix.job }}
    runs-on: 'ubuntu-latest'

    steps:

      - run: "jq <<<'${{ fromJSON(inputs.jobs) }}'"

      # Checkout / fetch. {{{

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          show-progress: false

      # }}}

      # Generate artifacts. {{{

      - name: Generate artifacts
        run: |
          set -x
          version="$(git describe --match='v[0-9]*')"
          echo "${version}" >version.txt
          artifacts=()
          case '${{ matrix.id }}' in
            android-arm) artifacts+=(koreader-android-arm-${version}.apk) ;;
            android-arm64) artifacts+=(koreader-android-arm64-${version}.apk) ;;
            linux-x86_64)
              artifacts+=("koreader-${version}-x86_64.AppImage")
              if [[ ${{ inputs.all_artifacts }} = true ]]; then
                artifacts+=("koreader-linux-x86_64-${version}.tar.xz" "koreader_${version#v}-1_amd64.deb")
              fi
              ;;
            kindlepw2)
              artifacts+=("koreader-kindlepw2-${version}.tar.xz")
              if [[ ${{ inputs.all_artifacts }} = true ]]; then
                artifacts+=("koreader-kindlepw2-${version}.targz" "koreader-kindlepw2-${version}.zip")
              fi
              ;;
            macos-arm64) artifacts+=("koreader-macos-11.0-arm64-${version}.7z") ;;
          esac
          for a in "${artifacts[@]}"; do
            case "${a}" in
              *.7z) 7z a "${a}" version.txt ;;
              *.apk | *.zip) zip "${a}" version.txt ;;
              *.AppImage) cp /usr/bin/true "${a}" ;;
              *.deb) ar q "${a}" version.txt ;;
              *.targz) tar czf "${a}" version.txt ;;
              *.tar.xz)
                a="${a%.xz}"
                tar cf "${a}" --record-size=512 version.txt
                size="$(stat -c %s "${a}")"
                xz -9 --block-list=$((size-512*2)),0 "$a"
                ;;
            esac
          done

      # }}}

      # Upload artifacts. {{{

      # Yes, we need to do this for each possible extension until
      # https://github.com/actions/upload-artifact#766 is resolved.

      - name: Upload artifact (7z)
        if: hashFiles('koreader-*.7z')
        uses: &UPLOAD_ARTIFACT actions/upload-artifact@v7
        with:
          archive: false
          path: koreader-*.7z

      - name: Upload artifact (apk)
        if: hashFiles('koreader-*.apk')
        uses: *UPLOAD_ARTIFACT
        with:
          archive: false
          path: koreader-*.apk

      - name: Upload artifact (appimage)
        if: hashFiles('koreader-*.AppImage')
        uses: *UPLOAD_ARTIFACT
        with:
          archive: false
          path: koreader-*.AppImage

      - name: Upload artifact (deb)
        if: hashFiles('koreader_*.deb')
        uses: *UPLOAD_ARTIFACT
        with:
          archive: false
          path: koreader_*.deb

      - name: Upload artifact (tar.xz)
        if: hashFiles('koreader-*.tar.xz')
        uses: *UPLOAD_ARTIFACT
        with:
          archive: false
          path: koreader-*.tar.xz

      - name: Upload artifact (targz)
        if: hashFiles('koreader-*.targz')
        uses: *UPLOAD_ARTIFACT
        with:
          archive: false
          path: koreader-*.targz

      - name: Upload artifact (zip)
        if: hashFiles('koreader-*.zip')
        uses: *UPLOAD_ARTIFACT
        with:
          archive: false
          path: koreader-*.zip

      # }}}

# vim: foldmethod=marker foldlevel=0
