name: Build Matrix

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      # Mandatory.
      jobs:
        required: true
        type: string
      # Optional.
      fail_fast:
        default: false
        type: boolean
      all_artifacts:
        default: false
        type: boolean
      test:
        default: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:

  build:

    strategy:
      fail-fast: ${{ inputs.fail_fast }}
      matrix:
        include: ${{ fromJSON(inputs.jobs) }}

    name: ${{ matrix.job }}
    runs-on: 'ubuntu-latest'

    steps:

      # Checkout. {{{

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          show-progress: false

      # }}}

      # Generate & upload artifacts. {{{

      - name: Generate artifacts
        if: matrix.target
        run: >
          ./.ci/artifact_generate.sh
          '${{ matrix.id }}'
          '${{ inputs.all_artifacts }}'
          '${{ matrix.macosx_deployment_target }}'

      - name: Upload artifacts
        uses: $/.github/actions/upload-artifacts
        with:
          patterns: |
            koreader-*.7z
            koreader-*.apk
            koreader-*.AppImage
            koreader-*.tar.xz
            koreader-*.targz
            koreader-*.zip
            koreader_*.deb

      # }}}

# vim: foldmethod=marker foldlevel=0
