name: Build

permissions:
  contents: read

on:
  workflow_call:
    inputs: &INPUTS
      jobs:
        description: 'Run the specified list of jobs'
        default: 'default'
        required: false
        type: string
      fail_fast:
        description: 'Stop remaining jobs on failure'
        default: false
        type: boolean
      all_artifacts:
        description: 'Generate all artifacts'
        default: false
        required: false
        type: boolean
      test:
        description: 'Run tests'
        default: true
        required: false
        type: boolean
  workflow_dispatch:
    inputs: *INPUTS

defaults:
  run:
    shell: bash

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
          sparse-checkout: .ci
      - name: Generate outputs
        id: generate
        run: |
          set -o noglob
          ./.ci/build.prepare.sh ${{ inputs.jobs }} >>"${GITHUB_OUTPUT}"
    outputs:
      jobs: ${{ steps.generate.outputs.jobs }}

  emulator:
    needs: prepare
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).emulator != '[]'
    name: Emulator
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).emulator }}
      fail_fast: ${{ inputs.fail_fast || true }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  android:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      contains(fromJSON("[\"android\"]", job.id) &&
      fromJSON(needs.prepare.outputs.jobs).android != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: Android
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).android }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  cervantes:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).cervantes != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: Cervantes
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).cervantes }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  kindle:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).kindle != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: Kindle
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).kindle }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  kobo:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).kobo != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: Kobo
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).kobo }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  linux:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).linux != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: Linux
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).linux }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  macos:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).macos != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: macOS
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).macos }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  pocketbook:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).pocketbook != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: pocketbook
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).pocketbook }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

  remarkable:
    needs: [prepare, emulator]
    if: |
      !cancelled() &&
      fromJSON(needs.prepare.outputs.jobs).remarkable != '[]' &&
      contains('skipped success', needs.emulator.result)
    name: reMarkable
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ fromJSON(needs.prepare.outputs.jobs).remarkable }}
      fail_fast: ${{ inputs.fail_fast }}
      all_artifacts: ${{ inputs.all_artifacts }}
      test: ${{ inputs.test }}

# vim: foldmethod=marker foldlevel=0
