name: Nightly

permissions:
  contents: read

on:
  schedule:
    # Every day at 6 AM (UTC, default branch only).
    - cron: '0 6 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    with:
      jobs: release
      all_artifacts: true

  release:
    name: Release
    needs: build
    if: |
      !cancelled() &&
      contains('success', needs.build.result)
    uses: ./.github/workflows/_release.yml
    secrets:
      # Yep, this is required to allow using the `release` environment
      # secret of the same name in the called workflow… Pretty evident,
      # right? ¯\_(ツ)_/¯
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      gh_repo: ${{ vars.RELEASE_GH_REPO || github.repository }}
