name: Nightly

permissions:
  contents: write

on:
  schedule:
    # Every day at 6 AM (UTC, default branch only).
    - cron: '0 6 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  
  nightly:

    name: Nightly
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          clean: false
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          show-progress: false
          sparse-checkout:

      - name: Update fork
        if: vars.ORIGIN_GH_REPO
        run: |
          set -x
          git pull --ff-only --tags ${{ vars.ORIGIN_GH_REPO }} ${{ github.ref }}
          git push --tags origin

      - name: Check if head is tagged
        id: head_check
        run: |
          git describe --tag --exact-match --match='v[0-9]*' || printf 'untagged=true' >>"${GITHUB_OUTPUT}"

      - name: Tag nightly
        if: steps.head_check.outputs.untagged
        run: |
          set -x
          git tag -a -f nightly
          git push -f origin refs/tags/nightly
