name: Push / PR

permissions:
  contents: read

on:
  push:
    # NOTE: ignore tags.
    branches:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # lint:
  #   name: Lint
  #   uses: ./.github/workflows/lint.yml

  build:
    name: Build
    # needs: lint
    uses: ./.github/workflows/build.yml
