name: Release

permissions:
  contents: read

on:
  push:
    # NOTE: stable tags only.
    tags:
      - "v*"
  # schedule:
  #   # Every day at 6 AM (UTC, default branch only).
  #   - cron: '0 6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GH_TELEMETRY: false

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: &ACTION_CHECKOUT actions/checkout@v7
        with:
          clean: false
          fetch-tags: true
          show-progress: false
          sparse-checkout: .ci
      - name: Check staleness
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.ci/release_staleness_check.sh
    outputs:
      stale: ${{ steps.check.outputs.stale }}
  
  build:
    name: Build
    needs: check
    if: needs.check.outputs.stale
    uses: ./.github/workflows/build.yml
    with:
      jobs: release
      fail_fast: true
      all_artifacts: true
      test: false

  sign_android_apks:
    name: Sign Android APKs
    needs: build
    environment: android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: *ACTION_CHECKOUT
        with:
          clean: false
          show-progress: false
          sparse-checkout: .ci
      - name: Download APKs
        uses: &ACTION_DOWNLOAD_ARTIFACT actions/download-artifact@v8
        with:
          merge-multiple: true
          path: assets
          pattern: "*.apk"
          skip-decompress: true
      - name: Sign APKs
        if: hashFiles('assets/*.apk')
        env:
          APK_SIGN_KEY_ALIAS: ${{ vars.APK_SIGN_KEY_ALIAS }}
          APK_SIGN_KEY_PASS: ${{ secrets.APK_SIGN_KEY_PASS }}
          APK_SIGN_STORE_BASE64: ${{ secrets.APK_SIGN_STORE_BASE64 }}
          APK_SIGN_STORE_PASS: ${{ secrets.APK_SIGN_STORE_PASS }}
        run: ./.ci/android_apks_sign.sh assets
      - name: Re-upload APKs
        if: hashFiles('assets/*.apk')
        uses: $/.github/actions/upload-artifacts
        with:
          overwrite: true
          patterns: assets/*.apk

  release:
    name: Release
    needs: sign_android_apks
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: *ACTION_CHECKOUT
        with:
          clean: false
          fetch-tags: true
          show-progress: false
          sparse-checkout: .ci
          token: ${{ secrets.GH_TOKEN }}
      - name: Download artifacts
        uses: *ACTION_DOWNLOAD_ARTIFACT
        with:
          merge-multiple: true
          path: assets
          skip-decompress: true
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./.ci/release_create.sh assets
