name: Release

permissions:
  contents: read

on:
  push:
    # NOTE: stable tags only.
    tags:
      - "v*"
  # schedule:
  #   # Every day at 6 AM (UTC, default branch only).
  #   - cron: '0 6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GH_TELEMETRY: false

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          fetch-tags: true
          show-progress: false
          sparse-checkout: .ci
      - name: Check staleness
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.ci/release_staleness_check.sh
    outputs:
      stale: ${{ steps.check.outputs.stale }}
  
  build:
    name: Build
    needs: check
    if: needs.check.outputs.stale
    uses: ./.github/workflows/build.yml
    with:
      jobs: release
      fail_fast: true
      all_artifacts: true
      test: false

  release:
    name: Release
    needs: build
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          fetch-tags: true
          show-progress: false
          sparse-checkout: .ci
          token: ${{ secrets.GH_TOKEN }}
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: assets
          skip-decompress: true
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APK_SIGN_KEY_ALIAS: ${{ vars.APK_SIGN_KEY_ALIAS }}
          APK_SIGN_KEY_PASS: ${{ secrets.APK_SIGN_KEY_PASS }}
          APK_SIGN_STORE_BASE64: ${{ secrets.APK_SIGN_STORE_BASE64 }}
          APK_SIGN_STORE_PASS: ${{ secrets.APK_SIGN_STORE_PASS }}
        run: ./.ci/release_create.sh assets
