name: Stable to OTA

permissions:
  contents: read

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  GH_TELEMETRY: false

jobs:

  upload_to_ota:

    name: Upload to OTA

    environment: release

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          # NOTE: we need a non-shallow clone for determining commit
          # count (`git rev-list --count $version`) when generating
          # F-Droid's metadata (`koreader-android-fdroid-latest`).
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
          show-progress: false
          sparse-checkout: .ci
          token: ${{ secrets.GH_TOKEN }}

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./.ci/stable_upload_to_ota.sh assets '${{ inputs.tag_name || github.event.release.tag_name }}'
