name: Stable

permissions:
  contents: read

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  update_ota:

    name: Update OTA

    environment: release

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          show-progress: false
          sparse-checkout: .ci

      - name: Update
        env:
          GH_REPO: ${{ inputs.gh_repo }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./.ci/stable.sh assets '${{ inputs.tag_name || github.event.release.tag_name }}'
